"""Frozen coefficients for the shadow ML classifier.

AUTO-GENERATED by scripts/export_ml_coeffs.py — do not hand-edit.
Multinomial logistic regression (impute-median -> standardize -> linear),
distilled to pure data so the scorer needs no sklearn/numpy in prod.
Trained on data/replay_full.csv (icon filter, feature_set=extended, n=715); exported 2026-06-15.
See docs/findings/ml-icon-coverage-shadow-2026-06-15.md.
"""
from __future__ import annotations

ML_MODEL: dict = {
    "trained_on": 'data/replay_full.csv (icon filter, feature_set=extended, n=715)',
    "trained_at": '2026-06-15',
    "n": 715,
    "feature_set": 'extended',
    "train_filter": 'icon',
    "train_population": {'munich_hpa': 1.0, 'innsbruck_hpa': 1.0, 'bolzano_hpa': 1.0, 'thermik_delta_hpa': 1.0, 'foehn_delta_hpa': 1.0, 'overnight_cloud_cover_pct': 1.0, 'morning_solar_radiation_wm2': 1.0, 'min_dew_point_spread_c': 1.0, 'rained_yesterday': 1.0, 'yesterday_precipitation_mm': 1.0, 'max_daytime_low_cloud_pct': 1.0, 'max_boundary_layer_height_m': 0.45734265734265733, 'max_cape_j_kg': 0.14685314685314685},
    "features": ['munich_hpa', 'innsbruck_hpa', 'bolzano_hpa', 'thermik_delta_hpa', 'foehn_delta_hpa', 'overnight_cloud_cover_pct', 'morning_solar_radiation_wm2', 'min_dew_point_spread_c', 'rained_yesterday', 'yesterday_precipitation_mm', 'max_daytime_low_cloud_pct', 'max_boundary_layer_height_m', 'max_cape_j_kg'],
    "labels": ['go', 'maybe', 'no_go'],
    "median": [1017.4, 1019.1, 1017.8, -1.5, -1.5, 73.125, 659.0, 2.8999999999999986, 0.0, 1.2, 33.0, 1000.0, 10.0],
    "mean": [1017.2560839160841, 1018.744055944056, 1017.3662937062937, -1.487972027972028, -1.3777622377622378, 62.668356643356645, 595.3398601398601, 3.279440559440559, 0.45314685314685316, 4.558321678321678, 44.62937062937063, 1013.9580419580419, 23.692307692307693],
    "scale": [6.2631278669904855, 6.0595970506668735, 5.686477356406638, 1.5593061750244286, 2.132694680635692, 35.01863389471135, 213.46701949286978, 2.5029514818694936, 0.49779994237641034, 6.887239440683493, 40.93027985116644, 314.6363173976213, 80.6412439174191],
    "coef": [
        [-0.002046013115460441, -0.0013113348330336375, 0.06176376248421769, -0.0031220815712773445, 0.16840872758802572, 0.015947047732780224, 0.5080086862189114, -0.3306863326205196, -0.10589202572544447, 0.00017463187402184802, 0.020733691616704065, -0.13748140728341343, 0.006014959352791167],
        [0.014369022137809166, 0.08915985995226189, 0.07298033907299543, -0.28876804866421146, -0.05873873083687842, -0.04837326466906534, -0.2383251143559246, 0.058147570334739364, 0.21585130119172108, -0.0832066064770497, -0.12361720287895105, 0.1292346335506358, -0.02796562210889064],
        [-0.012323009022348876, -0.08784852511922808, -0.134744101557214, 0.29189013023548616, -0.10966999675114675, 0.03242621693628385, -0.2696835718629865, 0.2725387622857816, -0.10995927546627711, 0.08303197460302793, 0.10288351126224722, 0.008246773732777674, 0.0219506627560994],
    ],
    "intercept": [-0.021586731703118554, 0.001267189323791618, 0.020319542379327003],
}
