"""Frozen coefficients for the thunderstorm advisory classifier.

AUTO-GENERATED by scripts/export_storm_coeffs.py — do not hand-edit.
Binary logistic (standardize -> linear -> sigmoid) over 9 afternoon convective
features (6 raw + 3 interactions; see storm_classifier.feature_vector). Distilled
to pure data so the scorer needs no sklearn/numpy in prod.

Trained on stored buoy gust-front labels (2021-2025 in-season, n=1067,
89 storms); exported 2026-06-24. Operating point:
leave-one-year-out POD 82% / FAR 84% / Peirce 0.431 (vs LI<=-2 baseline
Peirce 0.178). See docs/findings/thunderstorm-forecast-design-2026-06-24.md.
"""
from __future__ import annotations

# Feature order matches storm_classifier.feature_vector().
FEATURES: list[str] = [
    "cape", "li", "cin", "precip", "shear", "low_cloud",
    "cape_x_negli", "cape_x_shear", "shear_x_negli",
]
MEANS: list[float] = [262.72727272727275, 0.14957825679475156, -17.085285848172447, 1.3167760074976567, 13.932802249297092, 51.86316776007498, 881.0449859418932, 33.80052483598873, -4.68623242736645]
STDS: list[float] = [430.0072618078256, 3.318470547738752, 34.56682320022202, 3.138587381174035, 8.99093743040642, 40.62307623582039, 2245.3672463716025, 64.67390359264024, 55.52139864799664]
COEFS: list[float] = [-0.15888161796632108, -0.6582826090426794, 0.05426455889165701, 0.17997387070854767, 0.7613143622184801, 0.3796481475477911, 0.12393296130820002, 0.1716281392604016, -0.017241535518656058]
INTERCEPT: float = -0.5285765502710762
THRESHOLD: float = 0.3984319043269147
TRAINED_ON: str = "stored buoy gust-front, 2021-2025 in-season, n=1067"
TRAINED_AT: str = "2026-06-24"
