"""Calibrated thunderstorm advisory — a pure-Python logistic over afternoon
convective features. Drives the Caution advisory only; it never touches the
verdict (the LI veto was decoupled — see `docs/findings/li-decouple-2026-06-24.md`).

Replaces the single-threshold `rules.is_storm_risk` (LI ≤ −2), which on 5 seasons
of stored buoy gust-front ground truth scored POD 44% / FAR 87% / Peirce 0.178.
This 11-feature logistic (CAPE, LI, CIN, precip, precip-prob, deep shear, low
cloud + interactions) ≈ doubles the skill (Peirce 0.43) and at a recall-favouring
operating point catches ~82% of real gust-fronts (vs 44%) at a lower false-alarm
ratio. Design + evaluation: `docs/findings/thunderstorm-forecast-design-2026-06-24.md`.

Pure data: coefficients are frozen floats in `knowledge/storm_coeffs.py`
(auto-generated by `scripts/export_storm_coeffs.py`), scored in pure Python — **no
sklearn/numpy in either prod image**. Features are read from the same
`inputs.meteo` afternoon_* keys the training set is built from, so train/serve
can't drift. When the afternoon features are absent (archive host / pre-2021 /
legacy records), the advisory falls back to the LI ≤ −2 rule.
"""
from __future__ import annotations

import math

from oracle import config
from oracle.knowledge import storm_coeffs as _C

# Canonical raw afternoon features (window + definitions match pillars/meteo.py
# and scripts/export_storm_coeffs.py exactly — the train/serve contract).
_RAW_KEYS = ("cape", "li", "cin", "precip", "shear", "low_cloud")


def feature_vector(raw: dict) -> list[float] | None:
    """Build the model's 9-d feature vector (6 raw + 3 interactions) from a
    canonical raw dict. Returns None if any required raw feature is missing —
    the caller then falls back to the LI rule. (precipitation_probability is
    intentionally excluded: it is null on the historical-forecast archive used
    for training, so it would drift from the live API.)"""
    if any(raw.get(k) is None for k in _RAW_KEYS):
        return None
    cape, li, cin = raw["cape"], raw["li"], raw["cin"]
    precip, shear, low_cloud = raw["precip"], raw["shear"], raw["low_cloud"]
    return [
        cape, li, cin, precip, shear, low_cloud,
        cape * (-li),            # "loaded gun": instability × available energy
        cape * shear / 100.0,    # CAPE-shear severe-weather product
        shear * (-li),           # shear × instability
    ]


def raw_from_meteo_dict(m: dict) -> dict:
    """Canonical raw dict from a serialised `inputs.meteo` dict (afternoon_* keys)."""
    return {
        "cape": m.get("afternoon_cape_max_j_kg"),
        "li": m.get("afternoon_li_min"),
        "cin": m.get("afternoon_cin_min_j_kg"),
        "precip": m.get("afternoon_precip_mm"),
        "shear": m.get("afternoon_shear_kn"),
        "low_cloud": m.get("afternoon_low_cloud_max_pct"),
    }


def raw_from_snapshot(meteo) -> dict:
    """Canonical raw dict from a live `MeteoSnapshot`."""
    return {
        "cape": meteo.afternoon_cape_max_j_kg,
        "li": meteo.afternoon_li_min,
        "cin": meteo.afternoon_cin_min_j_kg,
        "precip": meteo.afternoon_precip_mm,
        "shear": meteo.afternoon_shear_kn,
        "low_cloud": meteo.afternoon_low_cloud_max_pct,
    }


def storm_probability(raw: dict) -> float | None:
    """Classifier storm probability in [0, 1], or None if features are missing."""
    vec = feature_vector(raw)
    if vec is None:
        return None
    z = [(x - mu) / sd for x, mu, sd in zip(vec, _C.MEANS, _C.STDS, strict=True)]
    logit = _C.INTERCEPT + sum(c * zi for c, zi in zip(_C.COEFS, z, strict=True))
    return 1.0 / (1.0 + math.exp(-logit))


def _li_fallback(li_min: float | None) -> bool:
    """The old single-threshold rule, used when afternoon features are absent."""
    return li_min is not None and li_min <= config.MIN_LIFTED_INDEX


def storm_advisory(raw: dict, li_fallback: float | None) -> bool:
    """Single source of truth for the storm advisory from a canonical raw dict.

    Uses the classifier when the afternoon features are present, else the LI rule.
    `li_fallback` is the morning `min_lifted_index` to fall back on.
    """
    prob = storm_probability(raw)
    if prob is None:
        return _li_fallback(li_fallback)
    # Operating point is the product knob in config (not the export's POD-matched
    # storm_coeffs.THRESHOLD, which a retrain would overwrite).
    return prob >= config.STORM_ADVISORY_THRESHOLD


def storm_advisory_from_meteo_dict(m: dict) -> bool:
    """Storm advisory from a serialised `inputs.meteo` dict (calibration/dashboard)."""
    return storm_advisory(raw_from_meteo_dict(m), m.get("min_lifted_index"))


def storm_advisory_from_snapshot(meteo) -> bool:
    """Storm advisory from a live `MeteoSnapshot` (the rules layer)."""
    return storm_advisory(raw_from_snapshot(meteo), meteo.min_lifted_index)
