"""Re-export the frozen coefficients for the shadow ML classifier.

This is the RETRAIN step for `src/oracle/knowledge/ml_coeffs.py`. It fits the
multinomial logistic regression on the replay calibration CSV and dumps the
~69 floats the pure-Python scorer (`oracle.ml_classifier`) consumes — so the
production images need no sklearn.

Dev-only: requires the `[ml]` extra (`uv pip install -e ".[ml]"`). It does NOT
import `oracle.ml` (that lives on the research branch); feature/label order
are pinned here as literals and asserted against the scorer's expectations.

    python scripts/export_ml_coeffs.py --csv data/replay_full.csv [--out src/oracle/knowledge/ml_coeffs.py]

After running, re-run `pytest tests/test_ml_classifier.py` — the golden test
will flag if the coefficients moved (expected after a genuine retrain; update
the golden if so).
"""
from __future__ import annotations

import argparse
import datetime as _dt

# Feature order MUST match oracle.ml_classifier / the training schema.
FEATURES = [
    "munich_hpa", "innsbruck_hpa", "bolzano_hpa", "thermik_delta_hpa", "foehn_delta_hpa",
    "overnight_cloud_cover_pct", "morning_solar_radiation_wm2", "min_dew_point_spread_c",
    "rained_yesterday", "yesterday_precipitation_mm", "max_daytime_low_cloud_pct",
]
LABELS = ["go", "maybe", "no_go"]
TARGET = "actual_verdict_thermal"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="data/replay_full.csv")
    ap.add_argument("--out", default="src/oracle/knowledge/ml_coeffs.py")
    args = ap.parse_args()

    import pandas as pd
    from sklearn.impute import SimpleImputer
    from sklearn.linear_model import LogisticRegression
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler

    df = pd.read_csv(args.csv)
    df = df[df[TARGET].isin(LABELS)].copy()
    if "storm_suspected" in df.columns:
        df = df[~df["storm_suspected"].fillna(False).astype(bool)]
    X = df[FEATURES].apply(pd.to_numeric, errors="coerce")
    y = df[TARGET].map({lab: i for i, lab in enumerate(LABELS)}).to_numpy()

    pipe = Pipeline([
        ("imp", SimpleImputer(strategy="median")),
        ("sc", StandardScaler()),
        ("clf", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42)),
    ]).fit(X, y)
    imp, sc, clf = pipe.named_steps["imp"], pipe.named_steps["sc"], pipe.named_steps["clf"]
    assert list(clf.classes_) == [0, 1, 2], "class order drifted from LABELS"

    bundle = {
        "trained_on": f"{args.csv} (n={len(y)})",
        "trained_at": _dt.date.today().isoformat(),
        "n": int(len(y)),
        "median": [float(x) for x in imp.statistics_],
        "mean": [float(x) for x in sc.mean_],
        "scale": [float(x) for x in sc.scale_],
        "coef": [[float(c) for c in row] for row in clf.coef_],
        "intercept": [float(x) for x in clf.intercept_],
    }

    lines = [
        '"""Frozen coefficients for the shadow ML classifier.',
        "",
        "AUTO-GENERATED by scripts/export_ml_coeffs.py — do not hand-edit.",
        "Multinomial logistic regression (impute-median -> standardize -> linear),",
        "distilled to pure data so the scorer needs no sklearn/numpy in prod.",
        f"Trained on {bundle['trained_on']}; exported {bundle['trained_at']}.",
        "See docs/findings/ml-shadow-classifier-design-2026-06-14.md.",
        '"""',
        "from __future__ import annotations",
        "",
        "ML_MODEL: dict = {",
        f'    "trained_on": {bundle["trained_on"]!r},',
        f'    "trained_at": {bundle["trained_at"]!r},',
        f'    "n": {bundle["n"]},',
        f'    "features": {FEATURES!r},',
        f'    "labels": {LABELS!r},',
        f'    "median": {bundle["median"]!r},',
        f'    "mean": {bundle["mean"]!r},',
        f'    "scale": {bundle["scale"]!r},',
        '    "coef": [',
        *(f"        {row!r}," for row in bundle["coef"]),
        "    ],",
        f'    "intercept": {bundle["intercept"]!r},',
        "}",
    ]
    with open(args.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {args.out} (n={bundle['n']}, exported {bundle['trained_at']})")


if __name__ == "__main__":
    main()
