"""Fit the thunderstorm-advisory logistic and freeze it to knowledge/storm_coeffs.py.

Train/serve contract: features are built through the **pillar's own code**
(`fetch_hourly_range` -> `snapshot_from_range` -> `storm_classifier.raw_from_snapshot`
-> `feature_vector`), the exact path the live forecast uses — so the exported model
can't drift from what it scores. Label = stored buoy gust-front from
`data/runs/<iso>.json` `ground_truth.machine.samples` (gust >= 22 kt AND afternoon
MSL pressure range >= 2 hPa), 2021-2025 in-season (CAPE/LI only exist 2021+).

Operating point favours recall (it's a safety warning): the threshold is picked,
leave-one-year-out, to hit ~82% POD. Prints LOYO POD/FAR/Peirce for sanity.

    uv pip install scikit-learn      # [ml] extra; not in either Dockerfile
    python3 scripts/export_storm_coeffs.py
"""
from __future__ import annotations

import asyncio
import datetime as dt
import json
import os

import numpy as np
from sklearn.linear_model import LogisticRegression

from oracle import storm_classifier as SC
from oracle.calibration import observed_storm
from oracle.config import OPEN_METEO_HISTORICAL_FORECAST_URL
from oracle.pillars import meteo as M

_TARGET_POD = 0.82
_COEFFS_PATH = "src/oracle/knowledge/storm_coeffs.py"


def buoy_gust_front(iso: str) -> bool | None:
    # Same definition as the dashboard's "actual" history row — shared helper so
    # the training label and the displayed observed-storm can't drift.
    f = f"data/runs/{iso}.json"
    if not os.path.exists(f):
        return None
    machine = (json.load(open(f)).get("ground_truth") or {}).get("machine") or {}
    return observed_storm(machine)


async def build_dataset():
    import calendar

    import httpx
    isos, vecs, ys = [], [], []
    async with httpx.AsyncClient(timeout=90) as client:
        for year in range(2021, 2026):
            for month in range(4, 11):  # Apr–Oct; per-month keeps payloads small
                start = dt.date(year, month, 1)
                end = dt.date(year, month, calendar.monthrange(year, month)[1])
                payload = await M.fetch_hourly_range(
                    start, end, client=client, host=OPEN_METEO_HISTORICAL_FORECAST_URL)
                times = M.parse_times(payload)
                d = start
                while d <= end:
                    iso = d.isoformat()
                    try:
                        snap = M.snapshot_from_range(payload, times, d)
                    except RuntimeError:
                        d += dt.timedelta(days=1)
                        continue
                    vec = SC.feature_vector(SC.raw_from_snapshot(snap))
                    lab = buoy_gust_front(iso)
                    if vec is not None and lab is not None:
                        isos.append(iso); vecs.append(vec); ys.append(lab)
                    d += dt.timedelta(days=1)
    return isos, np.array(vecs, float), np.array(ys, bool)


def _metrics(pred, y):
    tp = (pred & y).sum(); fp = (pred & ~y).sum(); fn = (~pred & y).sum(); tn = (~pred & ~y).sum()
    pod = tp / (tp + fn) if tp + fn else 0.0
    far = fp / (tp + fp) if tp + fp else 0.0
    return pod, far, pod - (fp / (fp + tn) if fp + tn else 0.0)


def main() -> None:
    isos, X, y = asyncio.run(build_dataset())
    yr = np.array([int(i[:4]) for i in isos])
    print(f"dataset: {len(y)} days, {y.sum()} gust-front storms ({y.mean():.1%})")

    mean, std = X.mean(0), X.std(0)
    std[std == 0] = 1.0
    Xs = (X - mean) / std

    # Leave-one-year-out probabilities -> pick a recall-favouring threshold.
    scores = np.zeros(len(y))
    for yy in np.unique(yr):
        tr, te = yr != yy, yr == yy
        m = LogisticRegression(class_weight="balanced", max_iter=2000, C=0.5).fit(Xs[tr], y[tr])
        scores[te] = m.predict_proba(Xs[te])[:, 1]
    thr = float(min(np.unique(scores), key=lambda t: abs(_metrics(scores >= t, y)[0] - _TARGET_POD)))
    pod, far, pk = _metrics(scores >= thr, y)
    base = _metrics(X[:, 1] <= -2, y)  # LI (feature 1) <= -2 baseline
    print(f"LOYO @threshold {thr:.3f}: POD {pod:.0%}  FAR {far:.0%}  Peirce {pk:.3f}")
    print(f"baseline LI<=-2:          POD {base[0]:.0%}  FAR {base[1]:.0%}  Peirce {base[2]:.3f}")

    # Final model: refit on all data for the frozen coefficients.
    final = LogisticRegression(class_weight="balanced", max_iter=2000, C=0.5).fit(Xs, y)
    coefs = final.coef_[0].tolist()
    intercept = float(final.intercept_[0])

    body = f'''"""Frozen coefficients for the thunderstorm advisory classifier.

AUTO-GENERATED by scripts/export_storm_coeffs.py — do not hand-edit.
Binary logistic (standardize -> linear -> sigmoid) over 9 afternoon convective
features (6 raw + 3 interactions; see storm_classifier.feature_vector). Distilled
to pure data so the scorer needs no sklearn/numpy in prod.

Trained on stored buoy gust-front labels (2021-2025 in-season, n={len(y)},
{int(y.sum())} storms); exported {dt.date.today().isoformat()}. Operating point:
leave-one-year-out POD {pod:.0%} / FAR {far:.0%} / Peirce {pk:.3f} (vs LI<=-2 baseline
Peirce {base[2]:.3f}). See docs/findings/thunderstorm-forecast-design-2026-06-24.md.
"""
from __future__ import annotations

# Feature order matches storm_classifier.feature_vector().
FEATURES: list[str] = [
    "cape", "li", "cin", "precip", "shear", "low_cloud",
    "cape_x_negli", "cape_x_shear", "shear_x_negli",
]
MEANS: list[float] = {mean.tolist()!r}
STDS: list[float] = {std.tolist()!r}
COEFS: list[float] = {coefs!r}
INTERCEPT: float = {intercept!r}
THRESHOLD: float = {thr!r}
TRAINED_ON: str = "stored buoy gust-front, 2021-2025 in-season, n={len(y)}"
TRAINED_AT: str = "{dt.date.today().isoformat()}"
'''
    with open(_COEFFS_PATH, "w") as fh:
        fh.write(body)
    print(f"wrote {_COEFFS_PATH}")


if __name__ == "__main__":
    main()
