"""Hyperparameter tuning for the ML ceiling spike.

Two-tier sweep on the 2017-2022 training era, using
`TimeSeriesSplit(gap=7)` per the research doc §3.6. The sweep is split
into a "tuning" phase (no significance tests, just pick the best by
mean Peirce across CV folds) and a "comparison" phase (re-fit the
winners on all training data, score on the 2023+ ICON-era holdout).

**Tier 1 — hyperparameter sweep** (research doc §3.7):
  HGB:        36 combos = max_iter × learning_rate × min_samples_leaf
  Logistic:   12 combos = C × class_weight

**Tier 2 — cost-sensitive class_weight for HGB** (research doc §3.4):
  Take the best Tier-1 HGB params, then sweep class_weight ∈
  {balanced, uniform, 1.5×, 2×, 3× GO-favoring}. 5 options × 3 folds.

The "uniform" class_weight is the no-intervention baseline the
research doc §3.5 recommends starting from before reweighting.
"balanced" is the current default. 1.5× / 2× / 3× are the
cost-sensitive variants — a 2× GO weight mirrors the project's
`MISSED_SESSION_COST = 2.0 / WASTED_DRIVE_COST = 1.0` ratio.

Reads `data/replay_full.csv` (regenerated by `oracle calibrate
--replayed`), runs the sweep, writes `data/ml/tuning_results.json`
+ a text summary to stdout.

Usage:
    python scripts/tune_ml.py
    # → writes data/ml/tuning_results.json
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from itertools import product
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import TimeSeriesSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from oracle.calibration import (
    heidke_skill_score,
    mean_cost as cal_mean_cost,
    peirce_skill_score,
)
from oracle.ml.dataset import LABEL_TO_INT, load_replay_csv, split_by_year
from oracle.ml.evaluate import _confusion_3x3
from oracle.ml.train import MIN_SAMPLES_LEAF, RANDOM_STATE


# --- Tier 1 grids --------------------------------------------------------

HGB_GRID: dict[str, list] = {
    "max_iter":          [100, 200, 400],
    "learning_rate":     [0.01, 0.05, 0.1],
    "min_samples_leaf":  [5, 10, 20, 50],
}  # 3 × 3 × 4 = 36 combos

LOGISTIC_GRID: dict[str, list] = {
    "C": [0.01, 0.1, 1.0, 10.0],
    "class_weight": [
        "balanced",                # current default
        {0: 1, 1: 1, 2: 1},        # uniform / no intervention
        {0: 2, 1: 1, 2: 1},        # mirror the 2:1 cost ratio
    ],
}  # 4 × 3 = 12 combos

# --- Tier 2: class_weight sweep for the best HGB -----------------------

HGB_CLASS_WEIGHTS: list = [
    "balanced",
    {0: 1, 1: 1, 2: 1},        # uniform
    {0: 1.5, 1: 1, 2: 1},      # mild go-favoring
    {0: 2, 1: 1, 2: 1},        # mirrors MISSED_SESSION_COST=2
    {0: 3, 1: 1, 2: 1},        # strong go-favoring
]


# --- model factories -----------------------------------------------------


def _make_hgb(params: dict | None = None) -> HistGradientBoostingClassifier:
    """HGB with the spike's defaults. `params` overrides any field."""
    defaults: dict = dict(
        max_iter=200,
        learning_rate=0.05,
        min_samples_leaf=MIN_SAMPLES_LEAF,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        early_stopping=False,
    )
    if params:
        defaults.update(params)
    return HistGradientBoostingClassifier(**defaults)


def _make_logistic(params: dict | None = None) -> Pipeline:
    """LR wrapped in a Pipeline(SimpleImputer → StandardScaler → LR) so
    it can fit the same NaN-containing matrix HGB sees. The
    `class_weight` and `C` are pipeline-step params; `params` is
    `{classifier__C: ..., classifier__class_weight: ...}`."""
    pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(max_iter=5000, random_state=RANDOM_STATE)),
    ])
    if params:
        # Translate the bare `C` / `class_weight` keys the user (and the
        # JSON output) expects into the pipeline-step-prefixed form
        # sklearn needs.
        overrides = {}
        if "C" in params:
            overrides["classifier__C"] = params["C"]
        if "class_weight" in params:
            overrides["classifier__class_weight"] = params["class_weight"]
        for k, v in params.items():
            if k not in ("C", "class_weight"):
                overrides[k] = v
        pipeline.set_params(**overrides)
    return pipeline


# --- scoring + CV --------------------------------------------------------


def _score_split(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    """Peirce + HSS + accuracy + mean_cost (at the default r=2) for one
    CV fold. Mirrors the scoring protocol in `oracle.ml.evaluate` so
    the tuning and final-test numbers are directly comparable."""
    confusion = _confusion_3x3(y_true, y_pred)
    return {
        "peirce":     float(peirce_skill_score(confusion)),
        "hss":        float(heidke_skill_score(confusion)),
        "accuracy":   float((y_true == y_pred).mean()),
        "mean_cost":  float(cal_mean_cost(confusion)),
    }


def _time_series_year_folds(
    X: np.ndarray, n_splits: int = 3, gap: int = 7,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """TimeSeriesSplit on chronologically-sorted rows. With the
    project's ~200 in-season days per year, n_splits=3 gives roughly
    one-year held-out folds (2017-2019 train / 2020 val, etc.)."""
    tscv = TimeSeriesSplit(n_splits=n_splits, gap=gap)
    return list(tscv.split(X))


def _run_grid(
    factory: Any,
    grid: dict,
    X: pd.DataFrame,
    y: np.ndarray,
    n_splits: int = 3,
    gap: int = 7,
    fixed_params: dict | None = None,
) -> list[dict]:
    """Run one hyperparam grid through TimeSeriesSplit CV.

    `factory(params)` builds a fresh model with the given params.
    `fixed_params` is merged into every combo (used for Tier 2 to
    fix the HGB hyperparams from Tier 1 while sweeping class_weight).

    Returns a list of {params, mean_*, per_fold: [...]} dicts sorted
    by mean_peirce descending.
    """
    keys = list(grid.keys())
    values = list(grid.values())
    combos = [dict(zip(keys, v)) for v in product(*values)]
    if fixed_params:
        combos = [{**fixed_params, **c} for c in combos]
    n_folds = n_splits
    print(f"  {len(combos)} combinations × {n_folds} folds = {len(combos) * n_folds} fits")
    folds = _time_series_year_folds(X.to_numpy(), n_splits=n_splits, gap=gap)

    results = []
    t0 = time.time()
    for i, combo in enumerate(combos):
        model = factory(combo)
        fold_scores: list[dict] = []
        for fold_idx, (train_idx, test_idx) in enumerate(folds):
            m = clone(model)
            m.fit(X.iloc[train_idx], y[train_idx])
            y_pred = m.predict(X.iloc[test_idx])
            scores = _score_split(y[test_idx], y_pred)
            scores["fold"] = fold_idx
            scores["train_n"] = int(len(train_idx))
            scores["test_n"] = int(len(test_idx))
            fold_scores.append(scores)
        results.append({
            "params": {k: (v if not isinstance(v, dict) else dict(v)) for k, v in combo.items()},
            "mean_peirce":    float(np.mean([s["peirce"] for s in fold_scores])),
            "mean_hss":       float(np.mean([s["hss"] for s in fold_scores])),
            "mean_accuracy":  float(np.mean([s["accuracy"] for s in fold_scores])),
            "mean_mean_cost": float(np.mean([s["mean_cost"] for s in fold_scores])),
            "per_fold": fold_scores,
        })
        if (i + 1) % 10 == 0 or i == len(combos) - 1:
            print(f"    ... {i + 1}/{len(combos)} done ({time.time() - t0:.1f}s)")
    results.sort(key=lambda r: r["mean_peirce"], reverse=True)
    return results


# --- main ---------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--csv", type=Path, default=Path("data/replay_full.csv"),
                   help="Replay CSV (Phase A schema; matches `oracle calibrate --replayed`)")
    p.add_argument("--out", type=Path, default=Path("data/ml/tuning_results.json"),
                   help="Output JSON path")
    p.add_argument("--label", type=str, default="thermal",
                   help="Target column: 'peak', 'duration', or 'thermal'")
    p.add_argument("--train-until-year", type=int, default=2022)
    p.add_argument("--test-from-year", type=int, default=2023)
    p.add_argument("--n-splits", type=int, default=3,
                   help="Number of TimeSeriesSplit folds (default 3 ≈ 1 year each)")
    p.add_argument("--gap", type=int, default=7,
                   help="Gap rows between train and val (default 7 ≈ 1 week, "
                        "mitigates short-range weather autocorrelation)")
    args = p.parse_args(argv)

    if not args.csv.exists():
        print(f"ERROR: {args.csv} not found. Run `oracle calibrate --csv {args.csv} --replayed` first.", file=sys.stderr)
        return 1

    # Load + year-blocked split.
    label_col = f"actual_verdict_{args.label}" if args.label != "peak" else "actual_verdict"
    data = load_replay_csv(args.csv, label_col=label_col)
    split = split_by_year(
        data, train_until_year=args.train_until_year, test_from_year=args.test_from_year, calibration_year=None,
    )
    print(f"Tuning sweep on {split.train.n_rows} train rows "
          f"({split.train.year.min()}-{split.train.year.max()}), "
          f"scoring on {split.test.n_rows} test rows "
          f"({split.test.year.min()}-{split.test.year.max()}).")
    print(f"TimeSeriesSplit: n_splits={args.n_splits}, gap={args.gap}.")

    # Rule baseline = `forecast_overall_resimulated` from the source CSV.
    raw_df = pd.read_csv(args.csv)
    test_days = set(split.test.day.tolist())
    baseline_rows = raw_df[raw_df["day"].isin(test_days)][["day", "forecast_overall_resimulated"]].set_index("day")
    baseline_pred_str = [baseline_rows.loc[d, "forecast_overall_resimulated"] for d in split.test.day]
    baseline_pred_int = np.array([LABEL_TO_INT[s] for s in baseline_pred_str])

    X_train = split.train.X
    y_train = split.train.y_int
    X_test = split.test.X
    y_test = split.test.y_int

    # Tier 1: HGB grid.
    print("\n[Tier 1] HGB hyperparameter sweep")
    hgb_results = _run_grid(
        _make_hgb, HGB_GRID, X_train, y_train,
        n_splits=args.n_splits, gap=args.gap,
    )
    hgb_best = hgb_results[0]
    print(f"  best mean Peirce: {hgb_best['mean_peirce']:+.3f}")
    print(f"  best params:       {hgb_best['params']}")

    # Tier 1: Logistic grid.
    print("\n[Tier 1] Logistic hyperparameter sweep")
    log_results = _run_grid(
        _make_logistic, LOGISTIC_GRID, X_train, y_train,
        n_splits=args.n_splits, gap=args.gap,
    )
    log_best = log_results[0]
    print(f"  best mean Peirce: {log_best['mean_peirce']:+.3f}")
    print(f"  best params:       {log_best['params']}")

    # Tier 2: class_weight sweep on the best HGB.
    print("\n[Tier 2] HGB class_weight sweep (fixed Tier-1 hyperparams)")
    cw_results = _run_grid(
        _make_hgb, {"class_weight": HGB_CLASS_WEIGHTS}, X_train, y_train,
        n_splits=args.n_splits, gap=args.gap,
        fixed_params=hgb_best["params"],
    )
    cw_best = cw_results[0]
    print(f"  best mean Peirce: {cw_best['mean_peirce']:+.3f}")
    print(f"  best class_weight: {cw_best['params']['class_weight']}")

    # Re-fit winners on the full training set.
    print("\nRe-fitting winners on the full training set + scoring on the test set...")
    hgb_final_params = {**hgb_best["params"], "class_weight": cw_best["params"]["class_weight"]}
    hgb_final = _make_hgb(hgb_final_params)
    hgb_final.fit(X_train, y_train)
    log_final = _make_logistic(log_best["params"])
    log_final.fit(X_train, y_train)

    hgb_test_pred = hgb_final.predict(X_test)
    log_test_pred = log_final.predict(X_test)
    hgb_test = _score_split(y_test, hgb_test_pred)
    log_test = _score_split(y_test, log_test_pred)
    base_test = _score_split(y_test, baseline_pred_int)

    # Text summary.
    print("\n" + "=" * 60)
    print("TUNING RESULTS — held-out 2023+ ICON-era test set")
    print("=" * 60)
    print(f"\n{'metric':<18s} {'HGB tuned':>11s} {'Logistic':>11s} {'rule':>11s}")
    for metric in ("peirce", "hss", "accuracy", "mean_cost"):
        print(f"  {metric:<16s}  "
              f"{hgb_test[metric]:>+11.3f}  "
              f"{log_test[metric]:>+11.3f}  "
              f"{base_test[metric]:>+11.3f}")
    print(f"\nHGB Tier-1+2 winner:  {hgb_final_params}")
    print(f"Logistic Tier-1 winner: {log_best['params']}")
    print()
    print("Top 5 HGB combos by mean Peirce (Tier 1):")
    for r in hgb_results[:5]:
        print(f"  Peirce={r['mean_peirce']:+.3f}  HSS={r['mean_hss']:+.3f}  "
              f"cost={r['mean_mean_cost']:.3f}  params={r['params']}")
    print("\nTop 5 Logistic combos by mean Peirce (Tier 1):")
    for r in log_results[:5]:
        print(f"  Peirce={r['mean_peirce']:+.3f}  HSS={r['mean_hss']:+.3f}  "
              f"cost={r['mean_mean_cost']:.3f}  params={r['params']}")
    print("\nClass_weight sweep (Tier 2, on the best HGB hyperparams):")
    for r in cw_results:
        print(f"  Peirce={r['mean_peirce']:+.3f}  HSS={r['mean_hss']:+.3f}  "
              f"cost={r['mean_mean_cost']:.3f}  class_weight={r['params']['class_weight']}")

    # Persist.
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        json.dump({
            "label": args.label,
            "train_until_year": args.train_until_year,
            "test_from_year": args.test_from_year,
            "n_splits": args.n_splits,
            "gap": args.gap,
            "hgb_best": hgb_best,
            "hgb_class_weight_best": cw_best,
            "logistic_best": log_best,
            "test_scores": {"hgb": hgb_test, "logistic": log_test, "rule": base_test},
            "hgb_final_params": hgb_final_params,
            "all_hgb_results": hgb_results,
            "all_logistic_results": log_results,
            "all_cw_results": cw_results,
        }, f, indent=2, default=str)
    print(f"\nFull results: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
